### ISSUE TITLE
initPjax called multiple times

### ISSUE THREAD

**Issue by ShadesOB** [kartik-v/yii2-grid#323] opened 2015-06-29 01:32 UTC
initPjax (client side) gets run on grid refresh. Which results in duplicate "pjax:complete" events being bound to grid object.

You can probably think of a better way to fix this. But attached below is a possible fix.

Located in yii2-grid\ColumnTrait.php line 311
<pre>
protected function initPjax($script = '')
    {

        if (!$this->grid->pjax || empty($script)) {
            return;
        }
        $scriptId = md5($script);

        $cont = 'jQuery("#' . $this->grid->pjaxSettings['options']['id'] . '")';
        $grid = $this->grid->options['id'];
        $view = $this->grid->getView();
        $view->registerJs(

            //Stops duplicate scripts running
            $cont.'.each(function(){
                if($(this).data("pjax:complete:'.$scriptId.'")){
                    return true;
                }
                '.$cont.'.data("pjax:complete:'.$scriptId.'",1);
                '.$cont.'.on("pjax:complete", function(){'.$script.'});
            });'
        );
    }
</pre>

**Comment by kartik-v** [comment] 2015-06-29 03:47
It can be resolved with a much better/neater fix. Will update.

**Comment by kartik-v** [comment] 2015-06-29 03:53
Ok this requires a bit of thought - will update again - because this will overwrite the scripts... Reopening it...

**Comment by kartik-v** [comment] 2015-06-29 04:23
Resolved via latest fix. Made it a little simpler for validating this.

**Closed** 2015-06-29 04:22 UTC
Labels: enhancement

**Comment by ShadesOB** [comment] 2015-06-29 06:39
This looks good. 
Possible idea for future may be to bind these on initial page load and then never do it via pjax.
Pros: not sending unneeded js. No need to unbind \ rebind.
cons: if js changes it won't update till page reload - if this works is it worth putting more time into it?

Also this is without going through any code to even see if it's possible.

Thanks for continued awesome work thought.  :D

**Comment by kartik-v** [comment] 2015-06-29 06:51
All of these are already initialized on page load. The problem is you are overwriting content via pjax which destroys the jquery elements and as a result all its event bindings. Hence this has to be parsed in something like `pjax:complete` (as is done now) to ensure the element exists for reinitializing.
