### ISSUE TITLE
Update issue: relational data in function($model, $key, $index, $widget)

### ISSUE THREAD

**Issue by xiandalisay** [kartik-v/yii2-grid#381] opened 2015-10-05 11:51 UTC
Before the update, this is my code for using an displaying relational data. In the new updates, an error pops out, 

```php
$attributes = [
        'rec_id' => [
            'label' => 'Organization Name',
            'type' => TabularForm::INPUT_STATIC,
            'staticValue' => function($model, $key, $index, $widget) {
            	return $model->rec->org->name;
            },
        ],
        'score' => [
            'label' => 'Score',
            'type' => TabularForm::INPUT_WIDGET,
            'widgetClass' => \kartik\widgets\TouchSpin::classname(), 
             'options'=> function($model, $key, $index, $widget) {
                    return 
                    [ 
                        //'readonly' => true,
                        'pluginOptions'=>[
                            'buttonup_class' => 'btn btn-primary', 
                            'buttondown_class' => 'btn btn-info', 
                            'buttonup_txt' => '<i class="glyphicon glyphicon-plus-sign"></i>', 
                            'buttondown_txt' => '<i class="glyphicon glyphicon-minus-sign"></i>',
                            'initval' => intval($model->score), 
                            'min' => 0,
                            'max' => intval($model->criterion->limit),
                            'prefix' => ' 0',
                            'postfix' => $model->criterion->limit,
                        ]
                    ];
                },
        ],
    ];
```

![capture](https://cloud.githubusercontent.com/assets/7392803/10279649/018d6a06-6b9a-11e5-8959-cf3839d74706.PNG)

If I moved the function($model, $key, $index, $widget) to an element in the form, it does nothing. The model->id is displayed Instead of the relational data.

```php
'options'=> 
                    [ 
                        //'readonly' => true,
                        'pluginOptions'=>[
                            'buttonup_class' => 'btn btn-primary', 
                            'buttondown_class' => 'btn btn-info', 
                            'buttonup_txt' => '<i class="glyphicon glyphicon-plus-sign"></i>', 
                            'buttondown_txt' => '<i class="glyphicon glyphicon-minus-sign"></i>',
                            'initval' => function($model, $key, $index, $widget) {
                                return intval($model->score); }, 
                            'min' => 0,
                            'max' => function($model, $key, $index, $widget) {
                                return intval($model->criterion->limit);},
                            'prefix' => ' 0',
                            'postfix' => function($model, $key, $index, $widget) {
                                return $model->criterion->limit;},
                        ]
                    ],
```

![capture](https://cloud.githubusercontent.com/assets/7392803/10279700/5976ee7c-6b9a-11e5-873a-4eb3b44967b3.PNG)

Instead of 'organization name' is displayed, the ID is displayed. Same as the criterion, and the score that displays Object

**Comment by kartik-v** [comment] 2015-10-21 07:45
This should be posted in `yii2-builder` and not here.

**Comment by kartik-v** [comment] 2015-10-21 07:50
This should be posted in `yii2-builder` and not here. In either case cannot reproduce this.You need to ensure you have the RIGHT updated code.

Check [tabular form basic usage 1](http://demos.krajee.com/builder-details/tabular-form#usage) where `publish_date` is rendered as a widget. 

If you have a reproducible use case you want to share - please raise an issue in the [yii2-builder repo](https://github.com/kartik-v/yii2-builder). Closing this.

**Closed** 2015-10-21 07:50 UTC
