### ISSUE TITLE
gridview.js:161 Uncaught TypeError: Cannot set property 'selectionColumn' of undefined

### ISSUE THREAD

**Issue by robov** [kartik-v/yii2-grid#518] opened 2016-07-02 08:43 UTC
When I use your basic setup as in : http://demos.krajee.com/grid-demo

and add only one checkbox column like this:
...
    $columns = [
        [
       
            'class'=>'kartik\grid\CheckboxColumn',
  ]];
...
Then I get on loading of the page:
gridview.js:161 Uncaught TypeError: Cannot set property 'selectionColumn' of undefined

Any idea what is going on?

**Comment by kartik-v** [comment] 2016-07-02 08:55
Get the latest release of the extension from dev-master. There are core yii framework changes that are causing this.

**Comment by robov** [comment] 2016-07-02 11:10
THANKS for the speedy reply...
Just did the composer upgrade
...
  - Updating kartik-v/yii2-grid dev-master (acbe6b3 => 7fa2e27)
    Checking out 7fa2e27ca021dada177db879ca04f7aab2d73e63
...
But the same problem exist. Am I missing something ?

**Comment by kartik-v** [comment] 2016-07-02 12:19
Not sure - cannot reproduce exactly. Can you cross check with the [demo example](http://demos.krajee.com/grid-demo) and confirm the differences if any?

**Comment by robov** [comment] 2016-07-02 12:53
This is my entire view: 
...

use kartik\grid\GridView;
    $columns = [
        [
        
            'class'=>'kartik\grid\CheckboxColumn',
  ]];
    ?>

    <?php
echo GridView::widget([
    'dataProvider'=>$dataProvider,
    'columns'=>$columns,
    'pjax'=>true, 
    'toolbar'=> false,
    'persistResize'=>false,
]);
...
When I change the checkboxcolumn into RadioColumn, then the error is not there

**Comment by kartik-v** [comment] 2016-07-02 17:50
Ok you must set the `GridView` widget's `id` property (since yii's checkbox column does not get initialized properly otherwise).

Refer this [note in docs](http://demos.krajee.com/grid#checkbox-column).

**Comment by robov** [comment] 2016-07-03 06:55
I did that in my original, just removed it by accident to clean up the example.
When I include an IDm then the problem is still there.

...
    <?php
echo GridView::widget([
    'id' => 'my_gridview_id',
    'dataProvider'=>$dataProvider,
    'columns'=>$columns,
    'pjax'=>false,  // true or false , the js error remains

**Comment by robov** [comment] 2016-07-03 06:55
p.s. How can I support your amazing work?

**Comment by kartik-v** [comment] 2016-07-03 17:34
> p.s. How can I support your amazing work?

@robov - thanks... you are free to submit enhancements (via PR).

**Comment by robov** [comment] 2016-07-04 06:13
Ok, I will do that...
Any idea how how I can fix my checkbox column in the mean time ?

**Comment by kartik-v** [comment] 2016-07-04 07:56
I suppose you should not be facing the errors you mention if you are running with the latest release and the other changes for grid id setting as mentioned (you can cross check with the demos page).

You may try cleaning up browser cache and restart and ensure your web assets are clean and retry.

**Comment by robov** [comment] 2016-07-04 08:16
Unfortunately I am still having the issues.
I cannot find a checkbox column demo... when I use the radiocolumn in my app, then the error is not there.. Do you have a checkbox column demo ?

**Comment by kartik-v** [comment] 2016-07-04 08:22
Its on the same [demo page](http://demos.krajee.com/grid-demo) The last column is the checkbox column.

**Comment by kartik-v** [comment] 2016-07-05 14:24
Closing this... let know if there is anything that can reproduce this and will reopen.

**Closed by kartik-v** 2016-07-05 14:24 UTC

**Comment by robov** [comment] 2016-08-14 13:04
I am still having this issue... this is the exact code:
```
$gridColumns = [
[
    'class'=>'kartik\grid\SerialColumn',
    'contentOptions'=>['class'=>'kartik-sheet-style'],
    'width'=>'36px',
    'header'=>'',
    'headerOptions'=>['class'=>'kartik-sheet-style']
],
[
    'class'=>'kartik\grid\CheckboxColumn',
    'headerOptions'=>['class'=>'kartik-sheet-style'],
],
];
        
        echo GridView::widget([
    'id' => 'kv-grid-demo',
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'columns'=>$gridColumns,
    'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
    'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    'filterRowOptions'=>['class'=>'kartik-sheet-style'],
    'pjax'=>true, // pjax is set to always true for this demo
    // set your toolbar
    'toolbar'=> [
        ['content'=>
            Html::button('<i class="glyphicon glyphicon-plus"></i>', ['type'=>'button', 'title'=>Yii::t('app', 'Add Book'), 'class'=>'btn btn-success', 'onclick'=>'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' '.
            Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['grid-demo'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=>Yii::t('app', 'Reset Grid')])
        ],
        '{export}',
        '{toggleData}',
    ],
    // set export properties
    'export'=>[
        'fontAwesome'=>true
    ],
    // parameters from the demo form
//    'bordered'=>$bordered,
//    'striped'=>$striped,
//    'condensed'=>$condensed,
//    'responsive'=>$responsive,
//    'hover'=>$hover,
//    'showPageSummary'=>$pageSummary,
//    'panel'=>[
//        'type'=>GridView::TYPE_PRIMARY,
//        'heading'=>$heading,
//    ],
//    'persistResize'=>false,
//    'exportConfig'=>$exportConfig,
]);   
```

This is the js includes...

```
</script><script src="/assets/54d7ba19/js/kv-grid-checkbox.js"></script>
<script src="/assets/a0905ab0/js/bootstrap.js"></script>
<script src="/assets/cf9f1cc1/dist/js/bootstrap-dialog.js"></script>
<script src="/assets/54d7ba19/js/kv-grid-export.js"></script>
<script src="/assets/54d7ba19/js/jquery.resizableColumns.js"></script>
<script src="/assets/adedf6fb/yii.js"></script>
<script src="/assets/63761dad/gridview.js"></script>
<script src="/assets/e2d7ee7b/jquery.pjax.js"></script>
<script src="/assets/33074546/js/site.js"></script>
<script src="/assets/276f9fb7/bootbox.js"></script>
<script src="/assets/33074546/js/jquery.pretty-text-diff.min.js"></script>
<script src="/assets/33074546/js/diff_match_patch.js"></script>
<script src="/assets/bedeeebc/jquery.qtip.js"></script>
```

I can even give you the link to the live page that show this error... When I click on the select all...
1) all the rows are highlighted (/ selected)
2) The boxes are not checked
3) the error appears : gridview.js:161 Uncaught TypeError: Cannot set property 'selectionColumn' of undefined

ANy ideas?

**Comment by robov** [comment] 2016-08-14 13:05
The grid is in a straight view (not in a form, not in pjax)

**Comment by kartik-v** [comment] 2016-08-16 19:09
As I mentioned, you need to check if you are running the latest code and have the latest JS and assets loaded. Also you need to check if your core yii2 files are also updated (the selectionColumn is a core yii2 grid functionality).
