### ISSUE TITLE
Have To Click ExpandRowColumn Twice For It To Open

### ISSUE THREAD

**Issue by chodges** [kartik-v/yii2-grid#303] opened 2015-05-20 23:16 UTC
I have a gridview in a tab.  And when I click the expand row column the first time I see the spinner but then nothing.  See picture:
![screen shot 2015-05-20 at 4 15 00 pm](https://cloud.githubusercontent.com/assets/197811/7738594/69a7559e-ff0b-11e4-81e0-97cb7fb31298.png)

So then I click to close the expanded row and click it again to open it and it works:

![screen shot 2015-05-20 at 4 16 10 pm](https://cloud.githubusercontent.com/assets/197811/7738617/93f37968-ff0b-11e4-91e8-3d11ef2efe60.png)

Any ideas why this might be happening?

**Comment by BrandonNC** [comment] 2015-06-02 20:29
I get the same problem and my GridView isn't in a tab even.  I also experience the problem using the demo on the main site (http://demos.krajee.com/grid-demo).

**Comment by BrandonNC** [comment] 2015-06-03 13:41
I resolved this issue by changing the following:

Around line 349 of kartik-v/yii2-grid/ExpandRowColumn.php, change:

```php
<div class="kv-expand-detail skip-export" style='display:none;'>
    {$content}
</div>
```

to:
```php
<div class="kv-expand-detail skip-export">
    {$content}
</div>
```

Basically just remove the style="display: none;" from the newly added details row.  I am not sure if this is the best solution or what side effects it may have, but it seems to work great for my situation.

**Comment by kartik-v** [comment] 2015-06-05 09:13
Showing the div content above can break the TABLE html displayed on certain browsers.

**Comment by kartik-v** [comment] 2015-06-05 09:17
Showing the div content above can break the TABLE html displayed on certain browsers. 

Also it will result in a logical mistake - because the content will always be shown (unless you have `expandOneOnly` set to `true`  - whereby expanding one row closes others).  Note the content should be shown only on toggling the data with expand row icon button.

**Comment by chodges** [comment] 2015-06-16 17:03
Yeah I tried that change and it didn't work at all for me -- the layout was completely destroyed.  So in the meantime I have set the grid to expand-all from inception.  Hope there's a fix coming for this soon.

**Comment by chodges** [comment] 2015-07-18 01:00
Just want to check in to see if there's any recommended way to fix this? As it stands now the feature is unusable for me because most of the use-cases have to do with the grids contained in tabs.  Thanks!

**Comment by BrandonNC** [comment] 2015-08-07 19:12
I too am looking for a real fix for this.

**Comment by kartik-v** [comment] 2015-10-21 07:10
Not sure I understand this issue entirely nor can reproduce. A normal grid with ExpandRowColumn rendered on a page works fine for both direct rendering via `detail` and/or ajax rendering via `detailUrl` as in [the demo page](http://demos.krajee.com/grid-demo).

If you are rendering the grid dynamically or within other content that is rendered dynamically via javascript (like tabs) - then this actually this lies beyond the scope of this widget.

The initialization of the ExpandRowColumn happens on Document ready. When you are trying to render content dynamically inside a tab - you must ensure that the javascript initialization of the ExpandRow content happens after TAB content is rendered.

**Comment by kartik-v** [comment] 2015-10-21 07:12
Not sure I understand this issue entirely nor can reproduce. A normal grid with ExpandRowColumn rendered on a page works fine for both direct rendering via `detail` and/or ajax rendering via `detailUrl` as in [the demo page](http://demos.krajee.com/grid-demo).

If you are rendering the grid dynamically or within other content that is rendered dynamically via other javascript (like tabs) - then this actually this lies beyond the scope of this widget.

The initialization of the ExpandRowColumn happens on Document ready. When you are trying to render content dynamically inside a tab - you must ensure that the javascript initialization of the ExpandRow content happens after TAB content is rendered. In some cases using yii's renderAjax method to render the dynamic tab content can help.

**Comment by BrandonNC** [comment] 2015-10-21 14:10
The problem occurs for me even on your demo page.  I am using Safari 9.0 on OS X 10.11, although the problem existed on older versions as well.  I had a co-worker try from his Linux machine running Firefox and he did not experience the problem, nor do I experience the problem when using Firefox for Mac.  I also tried Chrome for Mac and everything works fine there as well.  So it looks like the problem only occurs in Safari from what I can tell, not sure if that's true for chodges as well.

Here is a quick screen capture of the problem in Safari:
https://youtu.be/YdNAqcYBLLs

**Comment by chodges** [comment] 2015-11-17 12:30
I concur.  Even on the demo page the first time I click the expand row it does nothing.  Have to click it twice for it work.

**Closed** 2015-12-05 12:02 UTC

**Comment by kartik-v** [comment] 2015-12-05 12:03
Fixed via the latest commit. This is a Safari specific bug that does not show jQuery slideDown animations rightly. I have provided a fix with the commit - however you will not see a slide down animation in Safari because of the browser limitation.

**Comment by chodges** [comment] 2015-12-05 22:04
Thanks so much Kartik!
