### ISSUE TITLE
subGroupOf problem in 3.2.8 version

### ISSUE THREAD

**Issue by AlexNiko01** [kartik-v/yii2-grid#857] opened 2018-11-12 20:38 UTC
Hello. After update to 3.2.8 version I have problems with subGroupOf 2nd 3rd lvl. Works only with 1 subGroupOf in table. The example you show as solution ( http://demos.krajee.com/group-grid-demo/7 ) is works only with 'groupFooter' attribute, that I doesnt need in my table.
Thanks.

**Comment by kartik-v** [comment] 2018-11-13 09:41
It works without groupFooter as well. Hope you have ruled out browser cache and stale asset issue.

**Comment by kartik-v** [comment] 2018-11-21 04:45
Currently closing this as cannot reproduce your use case. If you have a method to reproduce this - please share an example - and can reopen this issue.

**Closed by kartik-v** 2018-11-21 04:45 UTC

**Comment by nimer-** [comment] 2020-10-06 09:19
Hi, i can confirm it really works only with groupfooter attribute. It definitively used to work :)

kv-grid-group.js  @version   3.2.7

using your example from: https://demos.krajee.com/group-grid-demo/7 :
```
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => null,
    'showPageSummary' => true,
    'pjax' => true,
    'hover' => true,
    'panel' => ['type' => 'primary', 'heading' => 'Grid Grouping Example'],
    'toggleDataContainer' => ['class' => 'btn-group mr-2'],
    'columns' => [
        // note that you MUST NOT have the first column as a grid group
        // to achieve that add a dummy hidden column like shown below
        ['class' => 'kartik\grid\SerialColumn', 'hidden' => true],
        ['attribute' => 'year',  'group' => true, 'groupFooter' => $gfYear, 'pageSummary' => 'Page Summary'],
        ['attribute' => 'month',  'group' => true, 'subGroupOf' => 1, 'groupFooter' => $gfMonth],
        ['attribute' => 'cat',  'group' => true, 'subGroupOf' => 2, 'groupFooter' => $gfCategory],
        ['attribute' => 'region',  'group' => true, 'subGroupOf' => 3, /*'groupFooter' => $gfRegion*/],
        ['attribute' => 'id', 'label' => 'ID', 'hAlign' => 'center', 'width' => '150px'],
        ['attribute' => 'amount', 'label' => 'Amount ($)', 'format' => ['decimal',  2], 'hAlign' => 'right', 'width' => '150px', 'pageSummary' => true],
    ],
]);
```
it looks like this:
![grid-group](https://user-images.githubusercontent.com/10073507/95182334-c1b85680-07c4-11eb-91c1-c96cc1759ea4.jpg)
