### ISSUE TITLE
Pajax reload on filters

### ISSUE THREAD

**Issue by diesan100** [kartik-v/yii2-grid#440] opened 2016-01-22 11:47 UTC
Hello,

I am having the next issue. 

I have a Gridview within a bootsrap modal window. I set up the pajax settings with an unique identifier as follows:

'pjax' => true,
'pjaxSettings'=>[
            'options' => ['id' => "docsAjaxListWrapperId"],
            'loadingCssClass' => true,
],

Then, if I sort the list by clicking on the column names (table header) it works just fine, which makes me believe that my settings are correct (without those settings the sorting feature reloads the entire page). 

However, and here becomes the issue, if I use any of the filters on the table header (Either dropdown filters or text search), then the whole page is reloaded.

For further information, the gridview is embedded in a modal window and rendered by renderAjax() and it seems all scripts are being correctly loaded.

Thanks in advance.

**Comment by diesan100** [comment] 2016-01-25 16:32
I have found out that the URL that is being called is different whether you reorder or you filter. So in the case a filter is applied, pjax forces the page reload.

**Comment by phpyii** [comment] 2016-02-25 02:03
+1

**Comment by phpyii** [comment] 2016-02-29 02:53
Refresh the page does not stop

**Comment by kartik-v** [comment] 2016-06-25 09:56
Cannot reproduce this use case. You may need to check your code.

Can you cross check this in [demo page](http://demos.krajee.com/grid-demo) and confirm if it works fine?

**Comment by kartik-v** [comment] 2016-06-25 09:58
Also refer #487. Am closing this since it needs to be handled at a developer level. In case you find something that can be improved - confirm so that this can be reopened.

**Closed by kartik-v** 2016-06-25 09:58 UTC
